-- StableMastersData.lua
local addonName, GHP = ...

if UnitClass and select(3, UnitClass("player")) ~= 3 then
    return
end

GHP.stable_masters = {
    {
        ["npcID"] = 9987,
        ["name"] = "Shoja'my",
        ["zone_name"] = "Durotar",
        ["zoneID"] = 1,
        ["coords"] = { { 52, 41.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 156988,
        ["name"] = "Shoja'my",
        ["zone_name"] = "Durotar",
        ["zoneID"] = 1,
        ["coords"] = { { 53.4, 40.8 }, { 53.6, 40.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10050,
        ["name"] = "Seikwa",
        ["zone_name"] = "Mulgore",
        ["zoneID"] = 7,
        ["coords"] = { { 47, 59.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 9981,
        ["name"] = "Sikwa",
        ["zone_name"] = "Northern Barrens",
        ["zoneID"] = 10,
        ["coords"] = { { 49, 57.4 }, { 49, 57.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 10063,
        ["name"] = "Reggifuz",
        ["zone_name"] = "Northern Barrens",
        ["zoneID"] = 10,
        ["coords"] = { { 67.4, 74.2 }, { 67.6, 74.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 43982,
        ["name"] = "Vernon Soursprye",
        ["zone_name"] = "Northern Barrens",
        ["zoneID"] = 10,
        ["coords"] = { { 62.4, 16.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43988,
        ["name"] = "Carthok",
        ["zone_name"] = "Northern Barrens",
        ["zoneID"] = 10,
        ["coords"] = { { 56.4, 39.8 }, { 56.6, 39.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 95609,
        ["name"] = "Sikwa",
        ["zone_name"] = "Northern Barrens",
        ["zoneID"] = 10,
        ["coords"] = { { 49, 57.6 }, { 49.2, 59 }, { 49.6, 58.8 }, { 49.6, 61 }, { 49.8, 60 }, { 50, 57.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 9976,
        ["name"] = "Tharlidun",
        ["zone_name"] = "Arathi Highlands",
        ["zoneID"] = 14,
        ["coords"] = { { 69, 33.4 }, { 69, 34 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 44123,
        ["name"] = "Emily Jackson",
        ["zone_name"] = "Arathi Highlands",
        ["zoneID"] = 14,
        ["coords"] = { { 40, 49 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 141737,
        ["name"] = "Emily Jackson",
        ["zone_name"] = "Arathi Highlands",
        ["zoneID"] = 14,
        ["coords"] = { { 39.4, 47.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 144140,
        ["name"] = "Tharlidun",
        ["zone_name"] = "Arathi Highlands",
        ["zoneID"] = 14,
        ["coords"] = { { 68, 35.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 232030,
        ["name"] = "Tharlidun",
        ["zone_name"] = "Arathi Highlands",
        ["zoneID"] = 14,
        ["coords"] = { { 68, 35.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 10058,
        ["name"] = "Greth",
        ["zone_name"] = "Badlands",
        ["zoneID"] = 15,
        ["coords"] = { { 18.2, 42.2 }, { 18.2, 42.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 48055,
        ["name"] = "Deedee Dropbolt",
        ["zone_name"] = "Badlands",
        ["zoneID"] = 15,
        ["coords"] = { { 65.4, 36.4 }, { 65.6, 36.4 }, { 65.6, 36.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 48095,
        ["name"] = "Katrina Lyons",
        ["zone_name"] = "Badlands",
        ["zoneID"] = 15,
        ["coords"] = { { 20.8, 56.2 }, { 21, 56.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44310,
        ["name"] = "Kroff",
        ["zone_name"] = "Blasted Lands",
        ["zoneID"] = 17,
        ["coords"] = { { 41.4, 12.8 }, { 41.6, 12.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 44330,
        ["name"] = "Gina Gellar",
        ["zone_name"] = "Blasted Lands",
        ["zoneID"] = 17,
        ["coords"] = { { 60.2, 16 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44335,
        ["name"] = "Willard C. Bennington",
        ["zone_name"] = "Blasted Lands",
        ["zoneID"] = 17,
        ["coords"] = { { 46, 85.4 }, { 46, 85.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10055,
        ["name"] = "Morganus",
        ["zone_name"] = "Tirisfal Glades",
        ["zoneID"] = 18,
        ["coords"] = { { 61.8, 52 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 9979,
        ["name"] = "Sarah Goode",
        ["zone_name"] = "Silverpine Forest",
        ["zoneID"] = 21,
        ["coords"] = { { 46, 42.4 }, { 46, 42.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 45498,
        ["name"] = "\"Salty\" Rocka",
        ["zone_name"] = "Silverpine Forest",
        ["zoneID"] = 21,
        ["coords"] = { { 44.4, 20.8 }, { 44.6, 20.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 47761,
        ["name"] = "Hank Ford",
        ["zone_name"] = "Western Plaguelands",
        ["zoneID"] = 22,
        ["coords"] = { { 47.2, 31.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 47866,
        ["name"] = "Lois Henderson",
        ["zone_name"] = "Western Plaguelands",
        ["zoneID"] = 22,
        ["coords"] = { { 47.8, 64 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 10057,
        ["name"] = "Theodore Mont Claire",
        ["zone_name"] = "Hillsbrad Foothills",
        ["zoneID"] = 25,
        ["coords"] = { { 56.8, 46.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 49395,
        ["name"] = "Shannon Lamb",
        ["zone_name"] = "Hillsbrad Foothills",
        ["zoneID"] = 25,
        ["coords"] = { { 36.2, 61.4 }, { 36.2, 61.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 49431,
        ["name"] = "Ansel Tunsleworth",
        ["zone_name"] = "Hillsbrad Foothills",
        ["zoneID"] = 25,
        ["coords"] = { { 59.6, 64.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 110357,
        ["name"] = "Theodore Mont Claire",
        ["zone_name"] = "Hillsbrad Foothills",
        ["zoneID"] = 25,
        ["coords"] = { { 56.8, 47 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 110889,
        ["name"] = "Shannon Lamb",
        ["zone_name"] = "Hillsbrad Foothills",
        ["zoneID"] = 25,
        ["coords"] = { { 36.2, 61.4 }, { 36.2, 61.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10061,
        ["name"] = "Killium Bouldertoe",
        ["zone_name"] = "The Hinterlands",
        ["zoneID"] = 26,
        ["coords"] = { { 14.4, 45.2 }, { 14.4, 45.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 14741,
        ["name"] = "Huntsman Markhor",
        ["zone_name"] = "The Hinterlands",
        ["zoneID"] = 26,
        ["coords"] = { { 79, 79.4 }, { 79, 79.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43766,
        ["name"] = "Roslyn Paxton",
        ["zone_name"] = "The Hinterlands",
        ["zoneID"] = 26,
        ["coords"] = { { 31.8, 57.4 }, { 32, 57.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43770,
        ["name"] = "Tathan Thunderstone",
        ["zone_name"] = "The Hinterlands",
        ["zoneID"] = 26,
        ["coords"] = { { 66.4, 45 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 9980,
        ["name"] = "Shelby Stoneflint",
        ["zone_name"] = "Dun Morogh",
        ["zoneID"] = 27,
        ["coords"] = { { 54, 51 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 109178,
        ["name"] = "Shelby Stoneflint",
        ["zone_name"] = "Dun Morogh",
        ["zoneID"] = 27,
        ["coords"] = { { 54, 51 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 47934,
        ["name"] = "Karn Cragcare",
        ["zone_name"] = "Searing Gorge",
        ["zoneID"] = 32,
        ["coords"] = { { 40.4, 68.4 }, { 40.4, 68.6 }, { 40.6, 68.4 }, { 40.6, 68.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 6749,
        ["name"] = "Erma",
        ["zone_name"] = "Elwynn Forest",
        ["zoneID"] = 37,
        ["coords"] = { { 42.8, 65.4 }, { 42.8, 65.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 113337,
        ["name"] = "Tassia Whisperglen",
        ["zone_name"] = "Deadwind Pass",
        ["zoneID"] = 42,
        ["coords"] = { { 50.4, 71.4 }, { 50.4, 71.6 }, { 50.6, 71.6 }, { 50.8, 71.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10062,
        ["name"] = "Steven Black",
        ["zone_name"] = "Duskwood",
        ["zoneID"] = 47,
        ["coords"] = { { 74, 46.2 }, { 74, 46.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 107863,
        ["name"] = "Steven Black",
        ["zone_name"] = "Duskwood",
        ["zoneID"] = 47,
        ["coords"] = { { 73.8, 46.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 9989,
        ["name"] = "Lina Hearthstove",
        ["zone_name"] = "Loch Modan",
        ["zoneID"] = 48,
        ["coords"] = { { 34.4, 48 }, { 34.6, 48 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 43979,
        ["name"] = "Gravin Steelbeard",
        ["zone_name"] = "Loch Modan",
        ["zoneID"] = 48,
        ["coords"] = { { 83.8, 62.4 }, { 84, 62.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 9982,
        ["name"] = "Penny",
        ["zone_name"] = "Redridge Mountains",
        ["zoneID"] = 49,
        ["coords"] = { { 26.2, 43 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 16094,
        ["name"] = "Durik",
        ["zone_name"] = "Northern Stranglethorn",
        ["zoneID"] = 50,
        ["coords"] = { { 38, 51.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 10049,
        ["name"] = "Hekkru",
        ["zone_name"] = "Swamp of Sorrows",
        ["zoneID"] = 51,
        ["coords"] = { { 47, 55.8 }, { 47.2, 55.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 47337,
        ["name"] = "Shecky Shrimpshoot",
        ["zone_name"] = "Swamp of Sorrows",
        ["zoneID"] = 51,
        ["coords"] = { { 71.6, 14.2 }, { 72, 14.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 47368,
        ["name"] = "Joran",
        ["zone_name"] = "Swamp of Sorrows",
        ["zoneID"] = 51,
        ["coords"] = { { 28.4, 33.2 }, { 28.4, 33.6 }, { 28.6, 33.2 }, { 28.6, 33.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10045,
        ["name"] = "Kirk Maxwell",
        ["zone_name"] = "Westfall",
        ["zoneID"] = 52,
        ["coords"] = { { 53, 53 }, { 56.4, 47.4 }, { 56.4, 47.6 }, { 56.6, 47.4 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10046,
        ["name"] = "Bethaine Flinthammer",
        ["zone_name"] = "Wetlands",
        ["zoneID"] = 56,
        ["coords"] = { { 10.4, 59.4 }, { 10.4, 59.6 }, { 10.6, 59.4 }, { 10.6, 59.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 43994,
        ["name"] = "Salustred",
        ["zone_name"] = "Wetlands",
        ["zoneID"] = 56,
        ["coords"] = { { 57.4, 40.4 }, { 57.6, 40.2 }, { 57.6, 40.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44007,
        ["name"] = "Shep Goldtend",
        ["zone_name"] = "Wetlands",
        ["zoneID"] = 56,
        ["coords"] = { { 26.2, 25.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10051,
        ["name"] = "Seriadne",
        ["zone_name"] = "Teldrassil",
        ["zoneID"] = 57,
        ["coords"] = { { 56.2, 52 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10085,
        ["name"] = "Jaelysia",
        ["zone_name"] = "Darkshore",
        ["zoneID"] = 62,
        ["coords"] = { { 50.4, 19.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10052,
        ["name"] = "Maluressian",
        ["zone_name"] = "Ashenvale",
        ["zoneID"] = 63,
        ["coords"] = { { 36.4, 50.4 }, { 36.4, 50.6 }, { 36.6, 50.4 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 15131,
        ["name"] = "Qeeju",
        ["zone_name"] = "Ashenvale",
        ["zoneID"] = 63,
        ["coords"] = { { 73.2, 60.4 }, { 73.2, 60.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43617,
        ["name"] = "Lursa",
        ["zone_name"] = "Ashenvale",
        ["zoneID"] = 63,
        ["coords"] = { { 12.6, 33.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43630,
        ["name"] = "Drek",
        ["zone_name"] = "Ashenvale",
        ["zoneID"] = 63,
        ["coords"] = { { 38.6, 42.4 }, { 38.6, 42.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43634,
        ["name"] = "Vorcha",
        ["zone_name"] = "Ashenvale",
        ["zoneID"] = 63,
        ["coords"] = { { 50.2, 65.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 134647,
        ["name"] = "Maluressian",
        ["zone_name"] = "Ashenvale",
        ["zoneID"] = 63,
        ["coords"] = { { 37.2, 51.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10048,
        ["name"] = "Gereck",
        ["zone_name"] = "Stonetalon Mountains",
        ["zoneID"] = 65,
        ["coords"] = { { 50.8, 63 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 41893,
        ["name"] = "Gelbin",
        ["zone_name"] = "Stonetalon Mountains",
        ["zoneID"] = 65,
        ["coords"] = { { 66.2, 64 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43017,
        ["name"] = "Fahlestad",
        ["zone_name"] = "Stonetalon Mountains",
        ["zoneID"] = 65,
        ["coords"] = { { 39.8, 32.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 43019,
        ["name"] = "Teldorae",
        ["zone_name"] = "Stonetalon Mountains",
        ["zoneID"] = 65,
        ["coords"] = { { 31.6, 61.4 }, { 31.8, 61.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 43021,
        ["name"] = "Adrius",
        ["zone_name"] = "Stonetalon Mountains",
        ["zoneID"] = 65,
        ["coords"] = { { 58.4, 56.6 }, { 58.6, 56.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 11104,
        ["name"] = "Shelgrayn",
        ["zone_name"] = "Desolace",
        ["zoneID"] = 66,
        ["coords"] = { { 65.4, 7.8 }, { 65.6, 7.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 11105,
        ["name"] = "Aboda",
        ["zone_name"] = "Desolace",
        ["zoneID"] = 66,
        ["coords"] = { { 24.8, 68.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 43877,
        ["name"] = "Fina Stillgrove",
        ["zone_name"] = "Desolace",
        ["zoneID"] = 66,
        ["coords"] = { { 57, 49.4 }, { 57, 49.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 9986,
        ["name"] = "Shyrka Wolfrunner",
        ["zone_name"] = "Feralas",
        ["zoneID"] = 69,
        ["coords"] = { { 74.4, 43.2 }, { 74.6, 43.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10059,
        ["name"] = "Antarius",
        ["zone_name"] = "Feralas",
        ["zoneID"] = 69,
        ["coords"] = { { 46.8, 45.4 }, { 46.8, 45.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44378,
        ["name"] = "Ajaye",
        ["zone_name"] = "Feralas",
        ["zoneID"] = 69,
        ["coords"] = { { 51.6, 48 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 44382,
        ["name"] = "Veir",
        ["zone_name"] = "Feralas",
        ["zoneID"] = 69,
        ["coords"] = { { 51, 18 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44384,
        ["name"] = "Sora",
        ["zone_name"] = "Feralas",
        ["zoneID"] = 69,
        ["coords"] = { { 41.4, 15.4 }, { 41.4, 15.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 10047,
        ["name"] = "Michael",
        ["zone_name"] = "Dustwallow Marsh",
        ["zoneID"] = 70,
        ["coords"] = { { 65.8, 45.4 }, { 65.8, 45.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 9985,
        ["name"] = "Laziphus",
        ["zone_name"] = "Tanaris",
        ["zoneID"] = 71,
        ["coords"] = { { 52.6, 27.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 98861,
        ["name"] = "Laziphus",
        ["zone_name"] = "Tanaris",
        ["zoneID"] = 71,
        ["coords"] = { { 52.2, 27.6 }, { 52.6, 27.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 43773,
        ["name"] = "Stella Boomboom",
        ["zone_name"] = "Azshara",
        ["zoneID"] = 76,
        ["coords"] = { { 56.8, 50 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 543,
        ["name"] = "Nalesette Wildbringer",
        ["zone_name"] = "Felwood",
        ["zoneID"] = 77,
        ["coords"] = { { 61.4, 25.4 }, { 61.6, 25.4 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 48216,
        ["name"] = "Hurah",
        ["zone_name"] = "Felwood",
        ["zoneID"] = 77,
        ["coords"] = { { 44.4, 28.4 }, { 44.4, 28.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 15722,
        ["name"] = "Squire Leoren Mal'derath",
        ["zone_name"] = "Silithus",
        ["zoneID"] = 81,
        ["coords"] = { { 53.2, 34.4 }, { 53.2, 34.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 11119,
        ["name"] = "Azzleby",
        ["zone_name"] = "Winterspring",
        ["zoneID"] = 83,
        ["coords"] = { { 58.6, 50.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 9977,
        ["name"] = "Sylista",
        ["zone_name"] = "Stormwind City",
        ["zoneID"] = 84,
        ["coords"] = { { 42.4, 60.4 }, { 42.4, 60.8 }, { 42.6, 60.2 }, { 42.6, 60.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 11069,
        ["name"] = "Jenova Stoneshield",
        ["zone_name"] = "Stormwind City",
        ["zoneID"] = 84,
        ["coords"] = { { 67, 37.4 }, { 67, 37.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44252,
        ["name"] = "Karin",
        ["zone_name"] = "Stormwind City",
        ["zoneID"] = 84,
        ["coords"] = { { 77.4, 67.4 }, { 77.4, 67.6 }, { 77.6, 67.6 }, { 77.8, 66.4 }, { 77.8, 67.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 194423,
        ["name"] = "Sylista",
        ["zone_name"] = "Stormwind City",
        ["zoneID"] = 84,
        ["coords"] = { { 40.6, 62.6 }, { 40.8, 62.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 9988,
        ["name"] = "Xon'cha",
        ["zone_name"] = "Orgrimmar",
        ["zoneID"] = 85,
        ["coords"] = { { 32.2, 64.8 }, { 32.2, 65.6 }, { 32.4, 64.4 }, { 32.6, 64.4 }, { 32.6, 64.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 44788,
        ["name"] = "Lonto",
        ["zone_name"] = "Orgrimmar",
        ["zoneID"] = 85,
        ["coords"] = { { 39.4, 48.4 }, { 39.4, 49.2 }, { 39.4, 49.6 }, { 39.6, 48.4 }, { 39.6, 49.2 }, { 39.6, 49.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 45789,
        ["name"] = "Bezzil",
        ["zone_name"] = "Orgrimmar",
        ["zoneID"] = 85,
        ["coords"] = { { 38, 86.4 }, { 38, 87 }, { 40.4, 80.4 }, { 40.4, 80.6 }, { 40.8, 80.4 }, { 40.8, 80.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 47764,
        ["name"] = "Murog",
        ["zone_name"] = "Orgrimmar",
        ["zoneID"] = 85,
        ["coords"] = { { 22, 89.8 }, { 61.8, 34.4 }, { 62, 35 }, { 62.4, 35.6 }, { 62.6, 35.4 }, { 62.6, 35.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 150981,
        ["name"] = "D'nosta",
        ["zone_name"] = "Orgrimmar",
        ["zoneID"] = 85,
        ["coords"] = { { 38, 86.2 }, { 38, 86.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 9984,
        ["name"] = "Ulbrek Firehand",
        ["zone_name"] = "Ironforge",
        ["zoneID"] = 87,
        ["coords"] = { { 68.4, 84.8 }, { 69, 84.6 }, { 69.4, 83.4 }, { 69.4, 84 }, { 69.6, 83.4 }, { 69.6, 83.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10054,
        ["name"] = "Bulrug",
        ["zone_name"] = "Thunder Bluff",
        ["zoneID"] = 88,
        ["coords"] = { { 44.2, 60.2 }, { 44.2, 60.6 }, { 44.4, 59.2 }, { 44.8, 60.6 }, { 45, 59.2 }, { 45, 59.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 10056,
        ["name"] = "Alassin",
        ["zone_name"] = "Darnassus",
        ["zoneID"] = 89,
        ["coords"] = { { 43.2, 29 }, { 43.4, 28.4 }, { 43.4, 29.6 }, { 43.6, 28.4 }, { 43.6, 29.4 }, { 43.6, 29.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 10053,
        ["name"] = "Anya Maulray",
        ["zone_name"] = "Undercity",
        ["zoneID"] = 90,
        ["coords"] = { { 66.4, 38 }, { 66.8, 38.6 }, { 67.4, 38 }, { 67.6, 37.4 }, { 67.6, 38 }, { 67.8, 38.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 16185,
        ["name"] = "Anathos",
        ["zone_name"] = "Eversong Woods",
        ["zoneID"] = 94,
        ["coords"] = { { 47.4, 47.2 }, { 47.6, 47.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 16665,
        ["name"] = "Paniar",
        ["zone_name"] = "Ghostlands",
        ["zoneID"] = 95,
        ["coords"] = { { 48.2, 31.6 }, { 48.4, 31.2 }, { 48.6, 31.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 17485,
        ["name"] = "Esbina",
        ["zone_name"] = "Azuremyst Isle",
        ["zoneID"] = 97,
        ["coords"] = { { 49, 49.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 16586,
        ["name"] = "Huntsman Torf Angerhoof",
        ["zone_name"] = "Hellfire Peninsula",
        ["zoneID"] = 100,
        ["coords"] = { { 54.4, 41 }, { 54.6, 41 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 16824,
        ["name"] = "Master Sergeant Lorin Thalmerok",
        ["zone_name"] = "Hellfire Peninsula",
        ["zoneID"] = 100,
        ["coords"] = { { 54.4, 62.6 }, { 54.6, 62.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 17896,
        ["name"] = "Kameel Longstride",
        ["zone_name"] = "Zangarmarsh",
        ["zoneID"] = 102,
        ["coords"] = { { 78.8, 64.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 18244,
        ["name"] = "Khalan",
        ["zone_name"] = "Zangarmarsh",
        ["zoneID"] = 102,
        ["coords"] = { { 31.8, 49.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 18250,
        ["name"] = "Joraal",
        ["zone_name"] = "Zangarmarsh",
        ["zoneID"] = 102,
        ["coords"] = { { 67.6, 49.4 }, { 67.6, 49.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 16764,
        ["name"] = "Arthaid",
        ["zone_name"] = "The Exodar",
        ["zoneID"] = 103,
        ["coords"] = { { 59.4, 24.4 }, { 59.4, 24.6 }, { 59.4, 25.8 }, { 59.8, 24.2 }, { 60, 25.4 }, { 60, 25.6 }, { 60.2, 26.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 221780,
        ["name"] = "Saranklei",
        ["zone_name"] = "The Exodar",
        ["zoneID"] = 103,
        ["coords"] = { { 60, 62.4 }, { 60.4, 62.6 }, { 60.6, 63 }, { 60.8, 63.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 19368,
        ["name"] = "Crinn Pathfinder",
        ["zone_name"] = "Shadowmoon Valley",
        ["zoneID"] = 104,
        ["coords"] = { { 37.4, 56 }, { 37.6, 56 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 21336,
        ["name"] = "Gedrah",
        ["zone_name"] = "Shadowmoon Valley",
        ["zoneID"] = 104,
        ["coords"] = { { 29.2, 29.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 19476,
        ["name"] = "Lor",
        ["zone_name"] = "Blade's Edge Mountains",
        ["zoneID"] = 105,
        ["coords"] = { { 53.4, 53.2 }, { 53.6, 53.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 22468,
        ["name"] = "Ogrin",
        ["zone_name"] = "Blade's Edge Mountains",
        ["zoneID"] = 105,
        ["coords"] = { { 75.4, 60.2 }, { 75.6, 60.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 22469,
        ["name"] = "Fiskal Shadowsong",
        ["zone_name"] = "Blade's Edge Mountains",
        ["zoneID"] = 105,
        ["coords"] = { { 36, 64.4 }, { 36, 64.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 23392,
        ["name"] = "Skyguard Stable Master",
        ["zone_name"] = "Blade's Edge Mountains",
        ["zoneID"] = 105,
        ["coords"] = { { 27.4, 52.4 }, { 27.4, 52.6 }, { 27.6, 52.4 }, { 27.6, 52.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 17666,
        ["name"] = "Astur",
        ["zone_name"] = "Bloodmyst Isle",
        ["zoneID"] = 106,
        ["coords"] = { { 55, 59.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 19018,
        ["name"] = "Wilda Bearmane",
        ["zone_name"] = "Nagrand",
        ["zoneID"] = 107,
        ["coords"] = { { 56.8, 40.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 19019,
        ["name"] = "Luftasia",
        ["zone_name"] = "Nagrand",
        ["zoneID"] = 107,
        ["coords"] = { { 55.8, 74.4 }, { 55.8, 74.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 18984,
        ["name"] = "Trag",
        ["zone_name"] = "Terokkar Forest",
        ["zoneID"] = 108,
        ["coords"] = { { 49.4, 44.4 }, { 49.4, 44.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 24905,
        ["name"] = "Leassian",
        ["zone_name"] = "Terokkar Forest",
        ["zoneID"] = 108,
        ["coords"] = { { 56.8, 53.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 24974,
        ["name"] = "Liza Cutlerflix",
        ["zone_name"] = "Netherstorm",
        ["zoneID"] = 109,
        ["coords"] = { { 32, 64.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 16656,
        ["name"] = "Shalenn",
        ["zone_name"] = "Silvermoon City",
        ["zoneID"] = 110,
        ["coords"] = { { 59.2, 34.6 }, { 82, 31.4 }, { 82.4, 31.6 }, { 82.8, 30.8 }, { 83.2, 31.6 }, { 83.4, 30.4 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 21517,
        ["name"] = "Ilthuril",
        ["zone_name"] = "Shattrath City",
        ["zoneID"] = 111,
        ["coords"] = { { 31, 32.4 }, { 43.4, 68.6 }, { 55.4, 79.4 }, { 55.4, 80.2 }, { 55.8, 79.4 }, { 55.8, 79.8 }, { 55.8, 80.8 }, { 56.6, 79.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 21518,
        ["name"] = "Oruhe",
        ["zone_name"] = "Shattrath City",
        ["zoneID"] = 111,
        ["coords"] = { { 24.4, 24.6 }, { 28.2, 48.6 }, { 28.4, 47.4 }, { 28.4, 47.6 }, { 28.6, 47.4 }, { 28.6, 47.6 }, { 41.4, 66.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 26044,
        ["name"] = "Durkot Wolfbrother",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 40.2, 55 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 26597,
        ["name"] = "Toby \"Mother Goose\" Ironbolt",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 57, 19 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 26721,
        ["name"] = "Halona Stormwhisper",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 77, 37.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 27010,
        ["name"] = "Celidh Aletracker",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 58.4, 68.4 }, { 58.4, 68.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 27065,
        ["name"] = "Breka Wolfsister",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 49.8, 10.4 }, { 49.8, 10.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 27194,
        ["name"] = "Trapper Saghani",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 78, 49 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 27385,
        ["name"] = "Ronald Anderson",
        ["zone_name"] = "Borean Tundra",
        ["zoneID"] = 114,
        ["coords"] = { { 56.6, 73 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 26504,
        ["name"] = "Soar Hawkfury",
        ["zone_name"] = "Dragonblight",
        ["zoneID"] = 115,
        ["coords"] = { { 37, 48.4 }, { 37, 48.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 27040,
        ["name"] = "Zybarus of Darnassus",
        ["zone_name"] = "Dragonblight",
        ["zoneID"] = 115,
        ["coords"] = { { 77.4, 50.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 27056,
        ["name"] = "Sentinel Sweetspring",
        ["zone_name"] = "Dragonblight",
        ["zoneID"] = 115,
        ["coords"] = { { 28.8, 56 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 27183,
        ["name"] = "Trapper Tikaani",
        ["zone_name"] = "Dragonblight",
        ["zoneID"] = 115,
        ["coords"] = { { 48.4, 74.4 }, { 48.4, 74.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 27948,
        ["name"] = "Risera",
        ["zone_name"] = "Dragonblight",
        ["zoneID"] = 115,
        ["coords"] = { { 61.4, 53.4 }, { 61.6, 53.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 28057,
        ["name"] = "Garmin Herzog",
        ["zone_name"] = "Dragonblight",
        ["zoneID"] = 115,
        ["coords"] = { { 76.8, 62.4 }, { 76.8, 62.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 26377,
        ["name"] = "Squire Percy",
        ["zone_name"] = "Grizzly Hills",
        ["zoneID"] = 116,
        ["coords"] = { { 59, 26.4 }, { 59, 26.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 26944,
        ["name"] = "Soulok Stormfury",
        ["zone_name"] = "Grizzly Hills",
        ["zoneID"] = 116,
        ["coords"] = { { 65, 47.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 27068,
        ["name"] = "Matthew Ackerman",
        ["zone_name"] = "Grizzly Hills",
        ["zoneID"] = 116,
        ["coords"] = { { 32.4, 59.4 }, { 32.4, 59.6 }, { 32.6, 59.4 }, { 32.6, 59.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 29250,
        ["name"] = "Tim Street",
        ["zone_name"] = "Grizzly Hills",
        ["zoneID"] = 116,
        ["coords"] = { { 13.8, 84.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 29251,
        ["name"] = "Kor",
        ["zone_name"] = "Grizzly Hills",
        ["zoneID"] = 116,
        ["coords"] = { { 13.8, 84.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 29740,
        ["name"] = "Craga Ironsting",
        ["zone_name"] = "Grizzly Hills",
        ["zoneID"] = 116,
        ["coords"] = { { 21.6, 64 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 23733,
        ["name"] = "Horatio the Stable Boy",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 58.6, 63 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 24066,
        ["name"] = "Artie Grizzlehand",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 60.6, 16 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 24067,
        ["name"] = "Mahana Frosthoof",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 49.4, 11 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 24154,
        ["name"] = "Mary Darrow",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 52, 66.4 }, { 52, 66.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 24350,
        ["name"] = "Robert Clarke",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 79, 30.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 27150,
        ["name"] = "Trapper Shesh",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 25.4, 59 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 29658,
        ["name"] = "Chelsea Reese",
        ["zone_name"] = "Howling Fjord",
        ["zoneID"] = 117,
        ["coords"] = { { 31.4, 41.4 }, { 31.6, 41.4 }, { 31.6, 41.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 30304,
        ["name"] = "Imhadria",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 44.2, 22.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 33854,
        ["name"] = "Thomas Partridge",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 71.4, 22.6 }, { 71.6, 22.6 }, { 71.8, 22.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 35290,
        ["name"] = "Steen Horngrass",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 75.6, 23.4 }, { 75.6, 23.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 35291,
        ["name"] = "Moonbell",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 75.8, 20.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 35344,
        ["name"] = "Bognar Ironfoot",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 69.6, 22 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 167090,
        ["name"] = "Bognar Ironfoot",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 69.8, 22 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 167112,
        ["name"] = "Steen Horngrass",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 75.6, 23.4 }, { 75.6, 23.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 167547,
        ["name"] = "Thomas Partridge",
        ["zone_name"] = "Icecrown",
        ["zoneID"] = 118,
        ["coords"] = { { 71.4, 22.6 }, { 71.6, 22.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 28047,
        ["name"] = "Hadrius Harlowe",
        ["zone_name"] = "Sholazar Basin",
        ["zoneID"] = 119,
        ["coords"] = { { 27.2, 59.4 }, { 27.2, 59.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 29906,
        ["name"] = "Heksi",
        ["zone_name"] = "The Storm Peaks",
        ["zoneID"] = 120,
        ["coords"] = { { 40.8, 86 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 29948,
        ["name"] = "Boarmaster Bragh",
        ["zone_name"] = "The Storm Peaks",
        ["zoneID"] = 120,
        ["coords"] = { { 28.6, 74.4 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 29959,
        ["name"] = "Andurg Slatechest",
        ["zone_name"] = "The Storm Peaks",
        ["zoneID"] = 120,
        ["coords"] = { { 30.4, 36.8 }, { 30.6, 36.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 29967,
        ["name"] = "Udoho Icerunner",
        ["zone_name"] = "The Storm Peaks",
        ["zoneID"] = 120,
        ["coords"] = { { 67.4, 50.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 30008,
        ["name"] = "Kari the Beastmaster",
        ["zone_name"] = "The Storm Peaks",
        ["zoneID"] = 120,
        ["coords"] = { { 49.8, 66 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 151615,
        ["name"] = "YZ-37 Biorearrangement Unit",
        ["zone_name"] = "The Storm Peaks",
        ["zoneID"] = 120,
        ["coords"] = { { 33, 58 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 28790,
        ["name"] = "Fala Softhoof",
        ["zone_name"] = "Zul'Drak",
        ["zoneID"] = 121,
        ["coords"] = { { 40.2, 65.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 30039,
        ["name"] = "Asgari",
        ["zone_name"] = "Zul'Drak",
        ["zoneID"] = 121,
        ["coords"] = { { 59, 57.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 25037,
        ["name"] = "Seraphina Bloodheart",
        ["zone_name"] = "Isle of Quel'Danas",
        ["zoneID"] = 122,
        ["coords"] = { { 50.2, 35.4 }, { 50.2, 35.6 }, { 50.6, 35.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 68989,
        ["name"] = "Beastblast Babblesnaff",
        ["zone_name"] = "The Lost Isles",
        ["zoneID"] = 174,
        ["coords"] = { { 28, 76.2 }, { 39.6, 27.8 }, { 42.4, 16.4 }, { 42.6, 16.4 }, { 45.2, 65 }, { 53, 35.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 43379,
        ["name"] = "Limiah Whitebranch",
        ["zone_name"] = "Mount Hyjal",
        ["zoneID"] = 198,
        ["coords"] = { { 19.4, 36.2 }, { 19.4, 36.6 }, { 19.6, 36.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 43408,
        ["name"] = "Aili Greenwillow",
        ["zone_name"] = "Mount Hyjal",
        ["zoneID"] = 198,
        ["coords"] = { { 63.2, 23 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 43494,
        ["name"] = "Oltarin Graycloud",
        ["zone_name"] = "Mount Hyjal",
        ["zoneID"] = 198,
        ["coords"] = { { 41.8, 45 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 50069,
        ["name"] = "Oltarin Graycloud",
        ["zone_name"] = "Mount Hyjal",
        ["zoneID"] = 198,
        ["coords"] = { { 41.8, 45 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 53780,
        ["name"] = "Limiah Whitebranch",
        ["zone_name"] = "Mount Hyjal",
        ["zoneID"] = 198,
        ["coords"] = { { 19.4, 36.2 }, { 19.6, 36.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 9983,
        ["name"] = "Kelsuwa",
        ["zone_name"] = "Southern Barrens",
        ["zoneID"] = 199,
        ["coords"] = { { 44, 33.4 }, { 44, 33.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 44346,
        ["name"] = "Brandon Merriweather",
        ["zone_name"] = "Southern Barrens",
        ["zoneID"] = 199,
        ["coords"] = { { 39, 11.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44347,
        ["name"] = "Werner Eastbrook",
        ["zone_name"] = "Southern Barrens",
        ["zoneID"] = 199,
        ["coords"] = { { 49, 68.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44348,
        ["name"] = "Carey Willis",
        ["zone_name"] = "Southern Barrens",
        ["zoneID"] = 199,
        ["coords"] = { { 66, 46.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 44349,
        ["name"] = "Munada",
        ["zone_name"] = "Southern Barrens",
        ["zoneID"] = 199,
        ["coords"] = { { 39.2, 19.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 44354,
        ["name"] = "Grantor",
        ["zone_name"] = "Southern Barrens",
        ["zoneID"] = 199,
        ["coords"] = { { 40.8, 69.4 }, { 40.8, 69.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 42966,
        ["name"] = "Chase Whithers",
        ["zone_name"] = "Abyssal Depths",
        ["zoneID"] = 204,
        ["coords"] = { { 56, 73 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 43151,
        ["name"] = "Shurrak",
        ["zone_name"] = "Abyssal Depths",
        ["zoneID"] = 204,
        ["coords"] = { { 53, 59.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 41903,
        ["name"] = "Tender Aru",
        ["zone_name"] = "Shimmering Expanse",
        ["zoneID"] = 205,
        ["coords"] = { { 49.4, 42 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 42875,
        ["name"] = "Miriam Brassbomb",
        ["zone_name"] = "Shimmering Expanse",
        ["zoneID"] = 205,
        ["coords"] = { { 49, 57.4 }, { 49, 57.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 42911,
        ["name"] = "Larok",
        ["zone_name"] = "Shimmering Expanse",
        ["zoneID"] = 205,
        ["coords"] = { { 51.4, 62.4 }, { 51.4, 62.6 }, { 51.6, 62.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 45297,
        ["name"] = "Beast-Handler Rustclamp",
        ["zone_name"] = "Deepholm",
        ["zoneID"] = 207,
        ["coords"] = { { 51.2, 50.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 45298,
        ["name"] = "Mule Driver Ironshod",
        ["zone_name"] = "Deepholm",
        ["zoneID"] = 207,
        ["coords"] = { { 47.4, 51.4 }, { 47.4, 51.6 }, { 47.6, 51.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 10060,
        ["name"] = "Grimestack",
        ["zone_name"] = "The Cape of Stranglethorn",
        ["zoneID"] = 210,
        ["coords"] = { { 41.4, 73.4 }, { 41.4, 73.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 44191,
        ["name"] = "Finzy Watchwoozle",
        ["zone_name"] = "The Cape of Stranglethorn",
        ["zoneID"] = 210,
        ["coords"] = { { 34.8, 27.4 }, { 34.8, 27.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 217185,
        ["name"] = "Fenegan Cobbler",
        ["zone_name"] = "Ruins of Gilneas",
        ["zoneID"] = 217,
        ["coords"] = { { 57.8, 56.4 }, { 58, 56.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 49554,
        ["name"] = "Kanath",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 75.4, 52.8 }, { 75.6, 52.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 49577,
        ["name"] = "Baird Darkfeather",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 55.4, 14.8 }, { 55.6, 14.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 49593,
        ["name"] = "Tarm Deepgale",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 48.6, 29.4 }, { 48.6, 29.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 49600,
        ["name"] = "Matthew Churchill",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 43.6, 57.4 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 49689,
        ["name"] = "Bonnie Hennigan",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 80.4, 77.2 }, { 80.6, 77.4 }, { 80.6, 77.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 49755,
        ["name"] = "Zay'hana",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 45, 76.6 }, { 45.2, 76.4 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 49767,
        ["name"] = "Rukh Zumtarg",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 53.8, 43 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 49790,
        ["name"] = "Kazz Fetchum",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 75.4, 16.8 }, { 75.6, 16.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 49803,
        ["name"] = "Kennen",
        ["zone_name"] = "Twilight Highlands",
        ["zoneID"] = 241,
        ["coords"] = { { 60.2, 58 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 48887,
        ["name"] = "Darwishi",
        ["zone_name"] = "Uldum",
        ["zoneID"] = 249,
        ["coords"] = { { 54.6, 33.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 49408,
        ["name"] = "Farah Tamina",
        ["zone_name"] = "Uldum",
        ["zoneID"] = 249,
        ["coords"] = { { 26.8, 7.4 }, { 27, 7.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66230,
        ["name"] = "Su Mi",
        ["zone_name"] = "The Jade Forest",
        ["zoneID"] = 371,
        ["coords"] = { { 28.6, 13 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 66241,
        ["name"] = "Hong the Kindly",
        ["zone_name"] = "The Jade Forest",
        ["zoneID"] = 371,
        ["coords"] = { { 46.4, 43.8 }, { 46.6, 43.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66243,
        ["name"] = "Pan the Kind Hand",
        ["zone_name"] = "The Jade Forest",
        ["zoneID"] = 371,
        ["coords"] = { { 54.8, 63 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66266,
        ["name"] = "Cheung",
        ["zone_name"] = "The Jade Forest",
        ["zoneID"] = 371,
        ["coords"] = { { 44.6, 84.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66717,
        ["name"] = "Beast-Haver Chi Chi",
        ["zone_name"] = "The Jade Forest",
        ["zoneID"] = 371,
        ["coords"] = { { 27.8, 46.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 66244,
        ["name"] = "Su the Tamer",
        ["zone_name"] = "Valley of the Four Winds",
        ["zoneID"] = 376,
        ["coords"] = { { 55.2, 49.4 }, { 55.2, 49.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 59413,
        ["name"] = "Cousin Mountainmusk",
        ["zone_name"] = "Kun-Lai Summit",
        ["zoneID"] = 379,
        ["coords"] = { { 42.2, 69.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 59509,
        ["name"] = "Herder Muskfree",
        ["zone_name"] = "Kun-Lai Summit",
        ["zoneID"] = 379,
        ["coords"] = { { 65.4, 61.4 }, { 65.4, 61.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66246,
        ["name"] = "Tigermaster Gai-Lin",
        ["zone_name"] = "Townlong Steppes",
        ["zoneID"] = 388,
        ["coords"] = { { 71.4, 57.4 }, { 71.4, 57.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66247,
        ["name"] = "Tigermaster Liu-Do",
        ["zone_name"] = "Townlong Steppes",
        ["zoneID"] = 388,
        ["coords"] = { { 74.8, 81.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66248,
        ["name"] = "Tigermistress Min-To",
        ["zone_name"] = "Townlong Steppes",
        ["zoneID"] = 388,
        ["coords"] = { { 50, 71.4 }, { 50, 71.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 63986,
        ["name"] = "Tracker Lang",
        ["zone_name"] = "Vale of Eternal Blossoms",
        ["zoneID"] = 390,
        ["coords"] = { { 60.4, 22.4 }, { 60.4, 22.6 }, { 60.6, 23 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 63988,
        ["name"] = "Jaul Hsu",
        ["zone_name"] = "Vale of Eternal Blossoms",
        ["zoneID"] = 390,
        ["coords"] = { { 84.6, 63.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 66245,
        ["name"] = "Mount-Haver Nik Nik",
        ["zone_name"] = "Vale of Eternal Blossoms",
        ["zoneID"] = 390,
        ["coords"] = { { 36, 75.2 }, { 36, 75.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 59310,
        ["name"] = "Teve Dawnchaser",
        ["zone_name"] = "Krasarang Wilds",
        ["zoneID"] = 418,
        ["coords"] = { { 59.2, 24.4 }, { 59.2, 24.6 }, { 61.8, 19.4 }, { 61.8, 19.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 66251,
        ["name"] = "Huntress Vael'yrie",
        ["zone_name"] = "Krasarang Wilds",
        ["zoneID"] = 418,
        ["coords"] = { { 67.2, 32.2 }, { 70.4, 28 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 66249,
        ["name"] = "Rough-rider Kim",
        ["zone_name"] = "Dread Wastes",
        ["zoneID"] = 422,
        ["coords"] = { { 55.8, 69.4 }, { 55.8, 69.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 66250,
        ["name"] = "Handler Kla'vik",
        ["zone_name"] = "Dread Wastes",
        ["zoneID"] = 422,
        ["coords"] = { { 53.6, 32.4 }, { 53.6, 32.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 62935,
        ["name"] = "Kama the Beast Tamer",
        ["zone_name"] = "The Veiled Stair",
        ["zoneID"] = 433,
        ["coords"] = { { 55.8, 75.2 }, { 55.8, 75.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 69252,
        ["name"] = "Ranger Shalan",
        ["zone_name"] = "Isle of Thunder",
        ["zoneID"] = 504,
        ["coords"] = { { 28.2, 51.4 }, { 28.2, 51.6 }, { 32.8, 32.4 }, { 32.8, 32.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 70184,
        ["name"] = "Tassia Whisperglen",
        ["zone_name"] = "Isle of Thunder",
        ["zoneID"] = 504,
        ["coords"] = { { 35.2, 90.4 }, { 35.2, 90.6 }, { 63.2, 73.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 77455,
        ["name"] = "Grimble the Pupmaster",
        ["zone_name"] = "Frostfire Ridge",
        ["zoneID"] = 525,
        ["coords"] = { { 38.8, 52 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 77461,
        ["name"] = "Wolfhandler Ang'cha",
        ["zone_name"] = "Frostfire Ridge",
        ["zoneID"] = 525,
        ["coords"] = { { 22, 56.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 77475,
        ["name"] = "Stu Whitetusk",
        ["zone_name"] = "Frostfire Ridge",
        ["zoneID"] = 525,
        ["coords"] = { { 21.4, 54.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 78698,
        ["name"] = "Ko'ari",
        ["zone_name"] = "Frostfire Ridge",
        ["zoneID"] = 525,
        ["coords"] = { { 52.4, 40.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 87006,
        ["name"] = "Tormak the Scarred",
        ["zone_name"] = "Frostfire Ridge",
        ["zoneID"] = 525,
        ["coords"] = { { 52.4, 20.4 }, { 52.4, 20.6 }, { 52.6, 20.4 }, { 52.6, 20.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 90992,
        ["name"] = "Dal Palesmoke",
        ["zone_name"] = "Tanaan Jungle",
        ["zoneID"] = 534,
        ["coords"] = { { 59.8, 45.4 }, { 59.8, 45.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 80833,
        ["name"] = "Beastmaster Tagh",
        ["zone_name"] = "Talador",
        ["zoneID"] = 535,
        ["coords"] = { { 70.8, 29.4 }, { 70.8, 29.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 80854,
        ["name"] = "Patrick Messer",
        ["zone_name"] = "Talador",
        ["zoneID"] = 535,
        ["coords"] = { { 69.4, 21.2 }, { 69.6, 21 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 81830,
        ["name"] = "Dakaari",
        ["zone_name"] = "Shadowmoon Valley",
        ["zoneID"] = 539,
        ["coords"] = { { 25.2, 7 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 84730,
        ["name"] = "Ertai",
        ["zone_name"] = "Shadowmoon Valley",
        ["zoneID"] = 539,
        ["coords"] = { { 59.2, 26.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 82553,
        ["name"] = "Villi Gobsplat",
        ["zone_name"] = "Spires of Arak",
        ["zoneID"] = 542,
        ["coords"] = { { 60.8, 71.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 81075,
        ["name"] = "Rangari Kolaan",
        ["zone_name"] = "Gorgrond",
        ["zoneID"] = 543,
        ["coords"] = { { 52.6, 59.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 82731,
        ["name"] = "Ribchewer",
        ["zone_name"] = "Gorgrond",
        ["zoneID"] = 543,
        ["coords"] = { { 45.8, 69.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 86808,
        ["name"] = "Keegan Firebeard",
        ["zone_name"] = "Nagrand",
        ["zoneID"] = 550,
        ["coords"] = { { 55.6, 59.4 }, { 86.6, 42.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 117013,
        ["name"] = "Jolanna",
        ["zone_name"] = "Broken Shore",
        ["zoneID"] = 646,
        ["coords"] = { { 53.4, 91.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 117014,
        ["name"] = "Togra",
        ["zone_name"] = "Broken Shore",
        ["zoneID"] = 646,
        ["coords"] = { { 50.2, 94.4 }, { 56.6, 85.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 117813,
        ["name"] = "Pan the Kind Hand",
        ["zone_name"] = "Broken Shore",
        ["zoneID"] = 646,
        ["coords"] = { { 43.4, 63 }, { 43.6, 63 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 97862,
        ["name"] = "Parek Splitfeather",
        ["zone_name"] = "Highmountain",
        ["zoneID"] = 650,
        ["coords"] = { { 52.8, 45.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 97874,
        ["name"] = "Haren Stonepath",
        ["zone_name"] = "Highmountain",
        ["zoneID"] = 650,
        ["coords"] = { { 53.2, 64 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 100661,
        ["name"] = "Pan the Kind Hand",
        ["zone_name"] = "Trueshot Lodge",
        ["zoneID"] = 739,
        ["coords"] = { { 58.4, 32 }, { 58.4, 33.4 }, { 58.4, 33.6 }, { 58.6, 33.6 }, { 58.8, 32.6 }, { 59, 32 }, { 59.4, 31.4 }, { 59.6, 33 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 126160,
        ["name"] = "Lead Rider Jerek",
        ["zone_name"] = "Krokuun",
        ["zoneID"] = 830,
        ["coords"] = { { 64.4, 62.4 }, { 64.4, 62.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 127752,
        ["name"] = "Raelaara the Kind",
        ["zone_name"] = "Krokuun",
        ["zoneID"] = 830,
        ["coords"] = { { 62.4, 47.8 }, { 62.6, 47.4 }, { 62.6, 47.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 124455,
        ["name"] = "Beast Handler Kooley",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 76.8, 16.4 }, { 76.8, 16.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 136004,
        ["name"] = "Johnathan Ebrills",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 44.4, 36.4 }, { 44.4, 36.6 }, { 44.6, 36.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 136064,
        ["name"] = "Dianelle Shadeclaw",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 44.8, 27.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 136082,
        ["name"] = "Saranklei",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 55.4, 25 }, { 55.6, 25 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 137333,
        ["name"] = "Habradu",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 51.2, 50.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 138850,
        ["name"] = "Birgita",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 77.2, 54.4 }, { 77.4, 54.8 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 140057,
        ["name"] = "Mitzi Pawsprinkle",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 64.4, 47.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 148168,
        ["name"] = "Tailmaster Tacklesnatz",
        ["zone_name"] = "Zuldazar",
        ["zoneID"] = 862,
        ["coords"] = { { 53.4, 57.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 129795,
        ["name"] = "Zam'cha",
        ["zone_name"] = "Nazmir",
        ["zoneID"] = 863,
        ["coords"] = { { 39, 43.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 131993,
        ["name"] = "Yash",
        ["zone_name"] = "Nazmir",
        ["zoneID"] = 863,
        ["coords"] = { { 66.8, 42 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 135750,
        ["name"] = "Beastmaster Veayeka",
        ["zone_name"] = "Nazmir",
        ["zoneID"] = 863,
        ["coords"] = { { 39.2, 78.4 }, { 39.4, 79.4 }, { 39.4, 79.6 }, { 39.6, 79.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 123730,
        ["name"] = "Man'zul",
        ["zone_name"] = "Vol'dun",
        ["zoneID"] = 864,
        ["coords"] = { { 43, 60.8 }, { 43.4, 60 }, { 43.6, 60 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 138701,
        ["name"] = "Teego",
        ["zone_name"] = "Vol'dun",
        ["zoneID"] = 864,
        ["coords"] = { { 57.2, 49.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 139827,
        ["name"] = "Vithur",
        ["zone_name"] = "Vol'dun",
        ["zoneID"] = 864,
        ["coords"] = { { 27, 51 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 139840,
        ["name"] = "Janraja",
        ["zone_name"] = "Vol'dun",
        ["zoneID"] = 864,
        ["coords"] = { { 52.4, 89.4 }, { 52.4, 89.6 }, { 52.6, 89.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 139841,
        ["name"] = "Akunda the Calm",
        ["zone_name"] = "Vol'dun",
        ["zoneID"] = 864,
        ["coords"] = { { 52.4, 89.4 }, { 52.4, 89.6 }, { 52.6, 89.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 144121,
        ["name"] = "Orville Manfred",
        ["zone_name"] = "Vol'dun",
        ["zoneID"] = 864,
        ["coords"] = { { 38.4, 34.4 }, { 38.6, 34.4 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 125035,
        ["name"] = "Dolan Northfield",
        ["zone_name"] = "Tiragarde Sound",
        ["zoneID"] = 895,
        ["coords"] = { { 51.4, 26 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 138160,
        ["name"] = "Tallelah Clearpath",
        ["zone_name"] = "Tiragarde Sound",
        ["zoneID"] = 895,
        ["coords"] = { { 87.4, 50.2 }, { 87.6, 50.4 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 143463,
        ["name"] = "Lionel Rowe",
        ["zone_name"] = "Tiragarde Sound",
        ["zoneID"] = 895,
        ["coords"] = { { 75.6, 50.8 }, { 76.6, 51.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 147727,
        ["name"] = "Lionel Rowe",
        ["zone_name"] = "Tiragarde Sound",
        ["zoneID"] = 895,
        ["coords"] = { { 75.8, 50.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 136142,
        ["name"] = "Klause Fairwind",
        ["zone_name"] = "Drustvar",
        ["zoneID"] = 896,
        ["coords"] = { { 19.4, 43.4 }, { 19.4, 43.6 }, { 19.6, 43.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 136233,
        ["name"] = "Klause Fairwind",
        ["zone_name"] = "Drustvar",
        ["zoneID"] = 896,
        ["coords"] = { { 19.8, 44.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 137010,
        ["name"] = "Willow Tempest",
        ["zone_name"] = "Drustvar",
        ["zoneID"] = 896,
        ["coords"] = { { 38.6, 52.4 }, { 38.8, 52.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 147677,
        ["name"] = "Willow Tempest",
        ["zone_name"] = "Drustvar",
        ["zoneID"] = 896,
        ["coords"] = { { 38.8, 52.4 }, { 38.8, 52.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 135386,
        ["name"] = "Calik the Skinny",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 43.2, 54.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 136674,
        ["name"] = "Madeline Netley",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 31.4, 67.2 }, { 31.6, 67.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 138108,
        ["name"] = "Beast Handler Khajuku",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 50.8, 33 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 138451,
        ["name"] = "Crabmaster Daijo",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 40.4, 36.4 }, { 40.4, 36.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 140551,
        ["name"] = "Officer Reynald",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 35.2, 48 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 141309,
        ["name"] = "Yoska Rainsinger",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 52.6, 77.4 }, { 53.4, 78.2 }, { 53.4, 79.2 }, { 53.6, 77.8 }, { 53.6, 78.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 141349,
        ["name"] = "Hayworth",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 58.4, 70.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 147610,
        ["name"] = "Officer Reynald",
        ["zone_name"] = "Stormsong Valley",
        ["zoneID"] = 942,
        ["coords"] = { { 34.4, 48.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 122696,
        ["name"] = "Beast Handler Kalatak",
        ["zone_name"] = "Dazar'alor",
        ["zoneID"] = 1165,
        ["coords"] = { { 45.8, 36.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 132066,
        ["name"] = "Beast Handler Sujani",
        ["zone_name"] = "Dazar'alor",
        ["zoneID"] = 1165,
        ["coords"] = { { 47.8, 89 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 132067,
        ["name"] = "Beast Handler Tahno",
        ["zone_name"] = "Dazar'alor",
        ["zoneID"] = 1165,
        ["coords"] = { { 59.4, 4.2 }, { 59.4, 4.6 }, { 59.8, 4.4 }, { 59.8, 4.6 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 133253,
        ["name"] = "Beast Handler Sonaba",
        ["zone_name"] = "Dazar'alor",
        ["zoneID"] = 1165,
        ["coords"] = { { 55, 14.4 }, { 55, 14.8 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 155941,
        ["name"] = "Tamer Orami",
        ["zone_name"] = "Nazjatar",
        ["zoneID"] = 1355,
        ["coords"] = { { 39.4, 55.4 }, { 39.6, 55.4 }, { 39.6, 55.6 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 150629,
        ["name"] = "Vera Lonelycog",
        ["zone_name"] = "Mechagon Island",
        ["zoneID"] = 1462,
        ["coords"] = { { 69.2, 30.4 }, { 69.2, 30.6 }, { 69.6, 30.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 156234,
        ["name"] = "Horrormaster Damnik",
        ["zone_name"] = "Revendreth",
        ["zoneID"] = 1525,
        ["coords"] = { { 49, 70 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 156291,
        ["name"] = "Shadowrider Neralva",
        ["zone_name"] = "Revendreth",
        ["zoneID"] = 1525,
        ["coords"] = { { 63.2, 61.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 163163,
        ["name"] = "Ogburn",
        ["zone_name"] = "Revendreth",
        ["zoneID"] = 1525,
        ["coords"] = { { 60.4, 39.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 166092,
        ["name"] = "Rasvan",
        ["zone_name"] = "Revendreth",
        ["zoneID"] = 1525,
        ["coords"] = { { 31.2, 49 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 167819,
        ["name"] = "Lester",
        ["zone_name"] = "Revendreth",
        ["zoneID"] = 1525,
        ["coords"] = { { 41.2, 47.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 171043,
        ["name"] = "Armandei",
        ["zone_name"] = "Revendreth",
        ["zoneID"] = 1525,
        ["coords"] = { { 63.6, 35 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 163250,
        ["name"] = "Farah Tamina",
        ["zone_name"] = "Uldum",
        ["zoneID"] = 1527,
        ["coords"] = { { 26.8, 7.4 }, { 26.8, 7.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 164249,
        ["name"] = "Darwishi",
        ["zone_name"] = "Uldum",
        ["zoneID"] = 1527,
        ["coords"] = { { 54.6, 33.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 162859,
        ["name"] = "Mount-Haver Nik Nik",
        ["zone_name"] = "Vale of Eternal Blossoms",
        ["zoneID"] = 1530,
        ["coords"] = { { 36, 73.4 }, { 36, 73.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 160178,
        ["name"] = "Eumelia",
        ["zone_name"] = "Bastion",
        ["zoneID"] = 1533,
        ["coords"] = { { 52.4, 48 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 160598,
        ["name"] = "Klystere",
        ["zone_name"] = "Bastion",
        ["zoneID"] = 1533,
        ["coords"] = { { 47.8, 73.4 }, { 47.8, 73.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 168760,
        ["name"] = "Klystere",
        ["zone_name"] = "Bastion",
        ["zoneID"] = 1533,
        ["coords"] = { { 58.2, 30 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 168778,
        ["name"] = "Eumelia",
        ["zone_name"] = "Bastion",
        ["zoneID"] = 1533,
        ["coords"] = { { 58, 29.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 174578,
        ["name"] = "Beastkeeper Gaelus",
        ["zone_name"] = "Bastion",
        ["zoneID"] = 1533,
        ["coords"] = { { 44.2, 33 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 175444,
        ["name"] = "Beastkeeper Ismene",
        ["zone_name"] = "Bastion",
        ["zoneID"] = 1533,
        ["coords"] = { { 35.2, 21.4 }, { 35.2, 21.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 157677,
        ["name"] = "Houndskeep Merrin",
        ["zone_name"] = "Maldraxxus",
        ["zoneID"] = 1536,
        ["coords"] = { { 39.4, 74.4 }, { 39.6, 74.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 161677,
        ["name"] = "Plimpton",
        ["zone_name"] = "Maldraxxus",
        ["zoneID"] = 1536,
        ["coords"] = { { 55, 70.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 161712,
        ["name"] = "Nana Redcap",
        ["zone_name"] = "Maldraxxus",
        ["zoneID"] = 1536,
        ["coords"] = { { 49.8, 54 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 174664,
        ["name"] = "Eggtender Ilven",
        ["zone_name"] = "Maldraxxus",
        ["zoneID"] = 1536,
        ["coords"] = { { 67.2, 45.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 160353,
        ["name"] = "Calico Mapleray",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 37.4, 38.2 }, { 37.6, 38.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 162433,
        ["name"] = "Finlar",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 60.4, 54 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 162434,
        ["name"] = "Littlewing",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 62.6, 35.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 164724,
        ["name"] = "Surnol",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 64.6, 19.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 168082,
        ["name"] = "Tinybell",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 49, 53 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 169150,
        ["name"] = "Littlewing",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 62.6, 35.4 }, { 62.6, 35.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 170571,
        ["name"] = "Timaeron",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 51, 33.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 170924,
        ["name"] = "Nortera",
        ["zone_name"] = "Ardenweald",
        ["zoneID"] = 1565,
        ["coords"] = { { 51, 70.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 144119,
        ["name"] = "Kasea Angerforge",
        ["zone_name"] = "",
        ["zoneID"] = 1584,
        ["coords"] = { { 47.2, 47.6 }, { 47.4, 47.4 }, { 47.6, 47.2 }, { 47.8, 45.4 }, { 47.8, 46.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 177157,
        ["name"] = "Caretaker Kah-Dee",
        ["zone_name"] = "Korthia",
        ["zoneID"] = 1961,
        ["coords"] = { { 60.4, 23 }, { 60.6, 23 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 180920,
        ["name"] = "Siloh",
        ["zone_name"] = "Zereth Mortis",
        ["zoneID"] = 1970,
        ["coords"] = { { 34.2, 66.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 188107,
        ["name"] = "Tionistrasz",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 62.8, 71.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 188445,
        ["name"] = "Cireni",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 43.2, 67.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 189202,
        ["name"] = "Uirreg Stoutbrow",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 25.8, 55.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 189738,
        ["name"] = "Ottukhandler Rutanko",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 54, 38.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 193021,
        ["name"] = "Beast Handler Tunse",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 65.8, 58.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 194605,
        ["name"] = "Bron",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 73.8, 54.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 199701,
        ["name"] = "Pan the Kind Hand",
        ["zone_name"] = "The Waking Shores",
        ["zoneID"] = 2022,
        ["coords"] = { { 24.4, 83.4 }, { 24.6, 83.4 }, { 24.6, 83.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 186183,
        ["name"] = "Beastmaster Nuqut",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 83.8, 25.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 186492,
        ["name"] = "Clarysse",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 30.2, 58.4 }, { 30.2, 58.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 190058,
        ["name"] = "Kokoslah",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 65.6, 24.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 191815,
        ["name"] = "Beastmaster Oken",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 45.6, 40.4 }, { 45.6, 40.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 192002,
        ["name"] = "Ibuko",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 80.6, 58 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 193008,
        ["name"] = "Goru the Shepherd",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 72, 78.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 195471,
        ["name"] = "Beastmaster Thalmaa",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 41.8, 60.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 195524,
        ["name"] = "Beastmaster Tirren",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 62, 41.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 196291,
        ["name"] = "Marren",
        ["zone_name"] = "Ohn'ahran Plains",
        ["zoneID"] = 2023,
        ["coords"] = { { 85.2, 35.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 186462,
        ["name"] = "Tatto",
        ["zone_name"] = "The Azure Span",
        ["zoneID"] = 2024,
        ["coords"] = { { 13.2, 48.8 }, { 13.8, 49.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 186860,
        ["name"] = "Aiwen Ironeye",
        ["zone_name"] = "The Azure Span",
        ["zoneID"] = 2024,
        ["coords"] = { { 65.2, 16.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 187020,
        ["name"] = "Jenis",
        ["zone_name"] = "The Azure Span",
        ["zoneID"] = 2024,
        ["coords"] = { { 63.2, 58.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 190892,
        ["name"] = "Zon'Wogi",
        ["zone_name"] = "The Azure Span",
        ["zoneID"] = 2024,
        ["coords"] = { { 19, 24 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 199688,
        ["name"] = "Jens Vilgrove",
        ["zone_name"] = "The Azure Span",
        ["zoneID"] = 2024,
        ["coords"] = { { 47, 40.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 199691,
        ["name"] = "Arcane Stabilizer",
        ["zone_name"] = "The Azure Span",
        ["zoneID"] = 2024,
        ["coords"] = { { 38, 60.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 187024,
        ["name"] = "Warden Krizzik",
        ["zone_name"] = "Thaldraszus",
        ["zoneID"] = 2025,
        ["coords"] = { { 60.2, 81.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 189025,
        ["name"] = "Lead Hostler Rhodani",
        ["zone_name"] = "Thaldraszus",
        ["zoneID"] = 2025,
        ["coords"] = { { 50.4, 68 }, { 50.6, 67.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 189353,
        ["name"] = "Yerili",
        ["zone_name"] = "Thaldraszus",
        ["zoneID"] = 2025,
        ["coords"] = { { 51, 43 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 189560,
        ["name"] = "Warden Krizzik",
        ["zone_name"] = "Thaldraszus",
        ["zoneID"] = 2025,
        ["coords"] = { { 60.2, 80.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 189561,
        ["name"] = "Warden Krizzik",
        ["zone_name"] = "Thaldraszus",
        ["zoneID"] = 2025,
        ["coords"] = { { 59.8, 81.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 185946,
        ["name"] = "Morganus",
        ["zone_name"] = "Tirisfal Glades",
        ["zoneID"] = 2070,
        ["coords"] = { { 59.2, 51.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 185947,
        ["name"] = "Morganus",
        ["zone_name"] = "Tirisfal Glades",
        ["zoneID"] = 2070,
        ["coords"] = { { 59.2, 51.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 186074,
        ["name"] = "Anya Maulray",
        ["zone_name"] = "Tirisfal Glades",
        ["zoneID"] = 2070,
        ["coords"] = { { 64.8, 66.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 185561,
        ["name"] = "Kaestrasz",
        ["zone_name"] = "Valdrakken",
        ["zoneID"] = 2112,
        ["coords"] = { { 46.4, 78.8 }, { 46.8, 78.4 }, { 46.8, 78.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 201102,
        ["name"] = "Uskogg",
        ["zone_name"] = "Zaralek Cavern",
        ["zoneID"] = 2133,
        ["coords"] = { { 43.2, 81.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 203294,
        ["name"] = "Vanndual",
        ["zone_name"] = "Zaralek Cavern",
        ["zoneID"] = 2133,
        ["coords"] = { { 57.6, 57.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 207760,
        ["name"] = "Alassin",
        ["zone_name"] = "Emerald Dream",
        ["zoneID"] = 2200,
        ["coords"] = { { 50.2, 61.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 208302,
        ["name"] = "Arno",
        ["zone_name"] = "Emerald Dream",
        ["zoneID"] = 2200,
        ["coords"] = { { 69.4, 54 }, { 69.6, 53.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 211355,
        ["name"] = "Darcia Dreamtongue",
        ["zone_name"] = "Emerald Dream",
        ["zoneID"] = 2200,
        ["coords"] = { { 53, 24.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 218416,
        ["name"] = "Heissanik",
        ["zone_name"] = "The Ringing Deeps",
        ["zoneID"] = 2214,
        ["coords"] = { { 58, 46 }, { 62.2, 46 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 225220,
        ["name"] = "Wheat",
        ["zone_name"] = "The Ringing Deeps",
        ["zoneID"] = 2214,
        ["coords"] = { { 54.4, 65.4 }, { 54.4, 65.6 }, { 58.6, 65.4 }, { 58.6, 65.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 228136,
        ["name"] = "Ellowie",
        ["zone_name"] = "The Ringing Deeps",
        ["zoneID"] = 2214,
        ["coords"] = { { 72, 83.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 217645,
        ["name"] = "Torran Dellain",
        ["zone_name"] = "Hallowfall",
        ["zoneID"] = 2215,
        ["coords"] = { { 69.2, 43.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 217990,
        ["name"] = "Vaedra Strayfend",
        ["zone_name"] = "Hallowfall",
        ["zoneID"] = 2215,
        ["coords"] = { { 42.2, 56.4 }, { 42.2, 56.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 216228,
        ["name"] = "Alassin",
        ["zone_name"] = "Amirdrassil",
        ["zoneID"] = 2239,
        ["coords"] = { { 48, 54.4 }, { 48, 54.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 226813,
        ["name"] = "Ramble Rider Enkor",
        ["zone_name"] = "Isle of Dorn",
        ["zoneID"] = 2248,
        ["coords"] = { { 59.4, 28 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 214951,
        ["name"] = "Shellwrangler Viz'kall",
        ["zone_name"] = "Azj-Kahet",
        ["zoneID"] = 2255,
        ["coords"] = { { 53.8, 53 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 224069,
        ["name"] = "Keyrra Pyregard",
        ["zone_name"] = "Azj-Kahet",
        ["zoneID"] = 2255,
        ["coords"] = { { 58.4, 19.2 }, { 58.6, 19.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 224510,
        ["name"] = "Olfii",
        ["zone_name"] = "Azj-Kahet",
        ["zoneID"] = 2255,
        ["coords"] = { { 77.8, 64.4 }, { 78, 64.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 224523,
        ["name"] = "Maetild Saberkrags",
        ["zone_name"] = "Azj-Kahet",
        ["zoneID"] = 2255,
        ["coords"] = { { 44.4, 67.4 }, { 44.6, 67.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 219376,
        ["name"] = "Kargand",
        ["zone_name"] = "Dornogal",
        ["zoneID"] = 2339,
        ["coords"] = { { 55.2, 67.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 238575,
        ["name"] = "Voidtamer Harpra",
        ["zone_name"] = "K'aresh",
        ["zoneID"] = 2371,
        ["coords"] = { { 60.4, 28.4 }, { 60.6, 28.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 245292,
        ["name"] = "Ka'barin",
        ["zone_name"] = "K'aresh",
        ["zoneID"] = 2371,
        ["coords"] = { { 49.2, 36.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 245440,
        ["name"] = "Ta'jol",
        ["zone_name"] = "K'aresh",
        ["zoneID"] = 2371,
        ["coords"] = { { 50.2, 59.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 243161,
        ["name"] = "Seraphina Bloodheart",
        ["zone_name"] = "Silvermoon City",
        ["zoneID"] = 2393,
        ["coords"] = { { 46.2, 55.4 }, { 46.2, 55.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 251302,
        ["name"] = "Shalenn",
        ["zone_name"] = "Silvermoon City",
        ["zoneID"] = 2393,
        ["coords"] = { { 27.4, 77.2 }, { 27.4, 77.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 254366,
        ["name"] = "Winaestra",
        ["zone_name"] = "Silvermoon City",
        ["zoneID"] = 2393,
        ["coords"] = { { 67.2, 66 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 242914,
        ["name"] = "Lucen Swiftmane",
        ["zone_name"] = "Eversong Woods",
        ["zoneID"] = 2395,
        ["coords"] = { { 47, 45.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 245770,
        ["name"] = "Paniar",
        ["zone_name"] = "Eversong Woods",
        ["zoneID"] = 2395,
        ["coords"] = { { 48.8, 66.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 240489,
        ["name"] = "Thorenara Stargazer",
        ["zone_name"] = "Voidstorm",
        ["zoneID"] = 2405,
        ["coords"] = { { 35.4, 59.2 }, { 35.6, 59.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 242658,
        ["name"] = "Callen Everfall",
        ["zone_name"] = "Voidstorm",
        ["zoneID"] = 2405,
        ["coords"] = { { 52.2, 67.4 }, { 52.2, 67.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 251116,
        ["name"] = "Tracker Aelix",
        ["zone_name"] = "Voidstorm",
        ["zoneID"] = 2405,
        ["coords"] = { { 42, 74.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 252679,
        ["name"] = "Taku",
        ["zone_name"] = "Harandar",
        ["zoneID"] = 2413,
        ["coords"] = { { 52.8, 52.4 }, { 52.8, 52.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 258671,
        ["name"] = "Lu'ka",
        ["zone_name"] = "Harandar",
        ["zoneID"] = 2413,
        ["coords"] = { { 69.6, 52 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 258677,
        ["name"] = "Sa'rena",
        ["zone_name"] = "Harandar",
        ["zoneID"] = 2413,
        ["coords"] = { { 35.4, 23.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 258725,
        ["name"] = "Mawraw",
        ["zone_name"] = "Harandar",
        ["zoneID"] = 2413,
        ["coords"] = { { 65.8, 23.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 258726,
        ["name"] = "Mokili",
        ["zone_name"] = "Harandar",
        ["zoneID"] = 2413,
        ["coords"] = { { 32, 67 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 253022,
        ["name"] = "Vari",
        ["zone_name"] = "Zul'Aman",
        ["zoneID"] = 2437,
        ["coords"] = { { 36.2, 24.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 255075,
        ["name"] = "Beastminder Tak'za",
        ["zone_name"] = "Zul'Aman",
        ["zoneID"] = 2437,
        ["coords"] = { { 45.2, 65.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 255187,
        ["name"] = "Uki",
        ["zone_name"] = "Zul'Aman",
        ["zoneID"] = 2437,
        ["coords"] = { { 47.2, 26 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 257151,
        ["name"] = "Oathbreaker Wrangler",
        ["zone_name"] = "Slayer's Rise",
        ["zoneID"] = 2444,
        ["coords"] = { { 35.4, 81.4 }, { 35.4, 81.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 235254,
        ["name"] = "Ba'simtal",
        ["zone_name"] = "Tazavesh",
        ["zoneID"] = 2472,
        ["coords"] = { { 47.2, 26.4 }, { 47.2, 26.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 28690,
        ["name"] = "Tassia Whisperglen",
        ["zone_name"] = "",
        ["zoneID"] = 4395,
        ["coords"] = { { 59, 38.6 }, { 59.4, 37.4 }, { 59.4, 37.6 }, { 59.6, 37.4 }, { 59.6, 37.8 }, { 59.6, 38.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 68993,
        ["name"] = "Fenegan Cobbler",
        ["zone_name"] = "",
        ["zoneID"] = 4714,
        ["coords"] = { { 37.8, 63.4 }, { 37.8, 63.6 }, { 42.6, 38.6 }, { 61, 91.4 }, { 61, 91.6 }, { 70.2, 40.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 68986,
        ["name"] = "Li the Tamer",
        ["zone_name"] = "",
        ["zoneID"] = 5736,
        ["coords"] = { { 53.4, 47.8 }, { 53.6, 47.4 }, { 53.6, 47.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 73632,
        ["name"] = "Cowardly Zue",
        ["zone_name"] = "",
        ["zoneID"] = 6771,
        ["coords"] = { { 40.4, 53.2 }, { 40.4, 53.6 }, { 40.8, 53.4 }, { 40.8, 54 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 79816,
        ["name"] = "Drokil",
        ["zone_name"] = "",
        ["zoneID"] = 7004,
        ["coords"] = { { 50, 56.8 }, { 51.2, 57 }, { 51.2, 57.6 }, { 51.2, 58.8 }, { 51.4, 60.8 }, { 51.4, 62.2 }, { 51.6, 61 }, { 51.8, 57.2 }, { 52, 58.2 }, { 52.2, 58.6 }, { 52.2, 62.2 }, { 52.8, 57.4 }, { 52.8, 57.6 }, { 55.2, 28.2 }, { 56, 27 }, { 56, 27.6 }, { 56.6, 27.2 }, { 56.6, 28.4 }, { 57.2, 29 }, { 57.8, 27.8 }, { 58, 27 }, { 58, 30.4 }, { 58, 30.6 }, { 58.8, 26 }, { 60.2, 29.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 79860,
        ["name"] = "Zagara",
        ["zone_name"] = "",
        ["zoneID"] = 7004,
        ["coords"] = { { 58, 47.4 }, { 58.2, 48.8 }, { 58.4, 48.4 }, { 59.2, 49.4 }, { 59.2, 49.8 }, { 59.6, 49 }, { 59.8, 49.8 }, { 60, 48.2 }, { 60.4, 33.4 }, { 60.4, 36.2 }, { 60.4, 50.8 }, { 60.8, 34.4 }, { 60.8, 48.4 }, { 60.8, 53 }, { 61, 34.6 }, { 61, 36.8 }, { 61.2, 36.4 }, { 61.4, 51.4 }, { 61.4, 52.2 }, { 61.6, 34.4 }, { 61.6, 36.6 }, { 61.6, 50.6 }, { 61.8, 53.6 }, { 62, 52.8 }, { 62.2, 35.2 }, { 62.4, 36.4 }, { 62.4, 52.2 }, { 62.6, 33.8 }, { 63, 34.6 }, { 63, 37.8 }, { 63, 53.4 }, { 63.4, 32.8 }, { 63.8, 34.6 }, { 64.2, 35.6 }, { 65.4, 33.4 }, { 65.4, 34.2 }, { 65.4, 34.6 }, { 65.8, 33 }, { 65.8, 33.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 86979,
        ["name"] = "Tormak the Scarred",
        ["zone_name"] = "",
        ["zoneID"] = 7004,
        ["coords"] = { { 58.2, 48.6 }, { 59.2, 49.6 }, { 60.2, 50 }, { 60.2, 50.6 }, { 60.4, 36.4 }, { 60.4, 36.6 }, { 60.6, 36.2 }, { 60.6, 50.4 }, { 61, 35 }, { 61.2, 34.4 }, { 61.2, 36.8 }, { 61.4, 52.6 }, { 61.8, 36.6 }, { 61.8, 52 }, { 62, 34.4 }, { 62, 36.4 }, { 62.2, 32.6 }, { 62.2, 35 }, { 62.2, 53.2 }, { 62.6, 52.4 }, { 62.8, 34.4 }, { 62.8, 34.8 }, { 63, 37.8 }, { 63, 53.6 }, { 63.6, 34.6 }, { 64.4, 34.2 }, { 64.6, 34.6 }, { 65.2, 33.8 }, { 65.4, 33.4 }, { 65.6, 33.4 }, { 65.6, 33.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 77381,
        ["name"] = "Raven",
        ["zone_name"] = "",
        ["zoneID"] = 7078,
        ["coords"] = { { 38.2, 60 }, { 38.2, 60.6 }, { 38.4, 59.4 }, { 38.6, 60 }, { 38.8, 60.6 }, { 39, 59.4 }, { 39.6, 60.8 }, { 40, 58.8 }, { 45.4, 40.2 }, { 45.6, 39.6 }, { 46, 38.2 }, { 46.2, 38.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 86973,
        ["name"] = "Keegan Firebeard",
        ["zone_name"] = "",
        ["zoneID"] = 7078,
        ["coords"] = { { 36.8, 58.4 }, { 37.2, 60.4 }, { 37.4, 56.2 }, { 37.4, 58.6 }, { 37.4, 60.6 }, { 37.8, 56 }, { 37.8, 61.4 }, { 37.8, 63 }, { 38, 58.4 }, { 38, 58.6 }, { 38, 61.6 }, { 38.4, 57.4 }, { 38.4, 60 }, { 38.6, 61.4 }, { 38.6, 61.6 }, { 39, 57.6 }, { 39, 60 }, { 39.2, 57.2 }, { 39.2, 64.4 }, { 39.4, 59.4 }, { 39.6, 57 }, { 39.8, 56.4 }, { 39.8, 59.6 }, { 40, 58.2 }, { 40, 59.4 }, { 40.2, 61.2 }, { 40.6, 61.2 }, { 41.2, 60.4 }, { 43, 41.4 }, { 43.4, 38.4 }, { 44.4, 40 }, { 44.6, 35 }, { 45, 39.8 }, { 45.2, 41.2 }, { 45.2, 42.6 }, { 45.4, 37.4 }, { 45.4, 37.8 }, { 45.4, 39.2 }, { 45.4, 42.2 }, { 45.6, 37.4 }, { 45.6, 38.4 }, { 45.6, 38.8 }, { 45.6, 42.8 }, { 45.8, 40.4 }, { 45.8, 41.4 }, { 46, 41.6 }, { 46.6, 37.6 }, { 46.6, 39.4 }, { 46.6, 41 }, { 46.6, 41.6 }, { 46.8, 37.4 }, { 46.8, 40.4 }, { 47.6, 40 }, { 47.6, 41.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 85963,
        ["name"] = "Orville Manfred",
        ["zone_name"] = "",
        ["zoneID"] = 7332,
        ["coords"] = { { 33.4, 64.2 }, { 33.4, 65.4 }, { 33.4, 65.6 }, { 33.6, 65.4 }, { 33.6, 65.6 }, { 34, 64.2 } },
        ["faction"] = "Alliance",
    },
    {
        ["npcID"] = 86052,
        ["name"] = "Ujia",
        ["zone_name"] = "",
        ["zoneID"] = 7333,
        ["coords"] = { { 76.4, 58.8 }, { 76.4, 59.6 }, { 77.2, 58.4 }, { 77.2, 59 }, { 77.2, 59.6 }, { 77.6, 58.4 }, { 77.6, 59.2 } },
        ["faction"] = "Horde",
    },
    {
        ["npcID"] = 97854,
        ["name"] = "Liza Galestride",
        ["zone_name"] = "",
        ["zoneID"] = 7731,
        ["coords"] = { { 53, 45.4 }, { 53.2, 47 }, { 53.4, 45.8 }, { 53.6, 45.4 }, { 53.6, 46.6 }, { 53.8, 46 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 151106,
        ["name"] = "YZ-85 Biorearrangement Unit",
        ["zone_name"] = "",
        ["zoneID"] = 8161,
        ["coords"] = { { 44.8, 37.6 }, { 45.2, 37.2 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 96507,
        ["name"] = "Tassia Whisperglen",
        ["zone_name"] = "",
        ["zoneID"] = 8574,
        ["coords"] = { { 45, 72.8 }, { 45.2, 74.2 }, { 45.2, 75.4 }, { 46, 76 }, { 46.2, 75 }, { 46.4, 72.6 }, { 46.4, 73.8 }, { 46.8, 71.6 }, { 46.8, 74.2 }, { 47.2, 75.2 }, { 47.4, 75.8 }, { 47.6, 72.4 }, { 47.6, 72.6 }, { 47.6, 74.2 }, { 47.6, 75.4 }, { 47.8, 75.6 }, { 49, 73.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 161666,
        ["name"] = "Austin Huxworth",
        ["zone_name"] = "",
        ["zoneID"] = 10424,
        ["coords"] = { { 52.4, 55.2 }, { 52.6, 55.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 167215,
        ["name"] = "Mithdran Dawntracker",
        ["zone_name"] = "",
        ["zoneID"] = 10424,
        ["coords"] = { { 52.4, 55.4 }, { 52.4, 55.6 }, { 52.6, 55.4 }, { 52.6, 55.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 156791,
        ["name"] = "Keeper Ta'saran",
        ["zone_name"] = "",
        ["zoneID"] = 10565,
        ["coords"] = { { 58.4, 74.2 }, { 58.4, 75.2 }, { 59, 73.8 }, { 59, 75.6 }, { 59.2, 75 }, { 59.6, 74 }, { 59.6, 74.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 159000,
        ["name"] = "Vasilica",
        ["zone_name"] = "",
        ["zoneID"] = 10986,
        ["coords"] = { { 69.2, 27.4 }, { 69.2, 27.8 }, { 69.2, 28.6 }, { 69.6, 27 }, { 70.4, 28.4 }, { 70.4, 28.6 }, { 71, 27.4 }, { 71, 28.4 }, { 71, 28.6 }, { 71.2, 29.6 }, { 71.6, 28.2 }, { 71.6, 28.6 }, { 71.6, 30.4 }, { 71.6, 30.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 174580,
        ["name"] = "Beastkeeper Krista",
        ["zone_name"] = "",
        ["zoneID"] = 11012,
        ["coords"] = { { 22.4, 30 }, { 22.4, 31.2 }, { 22.4, 31.8 }, { 22.8, 31.4 }, { 23, 31.8 }, { 23.2, 32.6 }, { 23.6, 32.4 }, { 23.6, 32.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 161100,
        ["name"] = "Darwishi",
        ["zone_name"] = "",
        ["zoneID"] = 12766,
        ["coords"] = { { 55.4, 33.2 }, { 55.6, 33.4 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 177489,
        ["name"] = "Timaeron",
        ["zone_name"] = "",
        ["zoneID"] = 13619,
        ["coords"] = { { 50.6, 33.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 180291,
        ["name"] = "Klystere",
        ["zone_name"] = "",
        ["zoneID"] = 13699,
        ["coords"] = { { 43, 49.6 }, { 43.4, 49 }, { 43.6, 48.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 194778,
        ["name"] = "Warden Krizzik",
        ["zone_name"] = "",
        ["zoneID"] = 13992,
        ["coords"] = { { 53.2, 52.2 }, { 53.4, 52.6 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 222432,
        ["name"] = "Tassia Whisperglen",
        ["zone_name"] = "",
        ["zoneID"] = 15177,
        ["coords"] = { { 45.4, 65.4 }, { 45.4, 65.8 }, { 45.6, 65.8 } },
        ["faction"] = "Neutral",
    },
    {
        ["npcID"] = 223027,
        ["name"] = "Tassia Whisperglen",
        ["zone_name"] = "",
        ["zoneID"] = 15177,
        ["coords"] = { { 33, 71.8 }, { 33.2, 71.4 } },
        ["faction"] = "Neutral",
    },
}
